<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>Tiltfile</string>
			<string>tiltfile</string>
		</array>
		<key>name</key>
		<string>Tiltfile</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#statement</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#expression</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>assignment-operator</key>
			<dict>
				<key>match</key>
				<string>//=|\+=|-=|/=|\*=|%=|=(?!=)</string>
				<key>name</key>
				<string>keyword.operator.assignment.starlark</string>
			</dict>
			<key>builtin-constant</key>
			<dict>
				<key>match</key>
				<string>\b(True|False|None)\b</string>
				<key>name</key>
				<string>keyword.illegal.name.starlark</string>
			</dict>
			<key>builtin-function</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(?&lt;!\.)\b(all|any|bool|dict|dir|enumerate|getattr|hasattr|hash|int|len|list|load|max|min|print|range|repr|reversed|sorted|str|tuple|type|zip)\b</string>
						<key>name</key>
						<string>support.function.starlark</string>
					</dict>
				</array>
			</dict>
			<key>code-tag</key>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.codetag.notation.starlark</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(?:\b(NOTE|XXX|HACK|FIXME|BUG|TODO)\b)</string>
			</dict>
			<key>constant-identifier</key>
			<dict>
				<key>match</key>
				<string>\b_*[[:upper:]][[:upper:]\d]*(_\w*)?\b</string>
				<key>name</key>
				<string>variable.other.constant.starlark</string>
			</dict>
			<key>dictionary-literal</key>
			<dict>
				<key>begin</key>
				<string>\{</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.dict.begin.starlark</string>
					</dict>
				</dict>
				<key>comment</key>
				<string>This also currently covers comprehensions.</string>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.dict.end.starlark</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>discouraged-semicolon</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\;$</string>
						<key>name</key>
						<string>invalid.deprecated.semicolon.starlark</string>
					</dict>
				</array>
			</dict>
			<key>discouraged-string-line-continuation</key>
			<dict>
				<key>match</key>
				<string>\\$</string>
				<key>name</key>
				<string>invalid.deprecated.language.starlark</string>
			</dict>
			<key>docstring</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>('''|""")</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.starlark</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(\1)</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.starlark</string>
							</dict>
						</dict>
						<key>name</key>
						<string>comment.block.documentation.starlark</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#code-tag</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#docstring-content</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>(r)('''|""")</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.type.string.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.starlark</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(\2)</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.starlark</string>
							</dict>
						</dict>
						<key>name</key>
						<string>comment.block.documentation.starlark</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#string-consume-escape</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#code-tag</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>('|")</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.starlark</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(\1)|((?&lt;!\\)\n)</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>invalid.illegal.newline.starlark</string>
							</dict>
						</dict>
						<key>name</key>
						<string>comment.line.documentation.starlark</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#code-tag</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#docstring-content</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>(r)('|")</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.type.string.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.starlark</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(\2)|((?&lt;!\\)\n)</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>invalid.illegal.newline.starlark</string>
							</dict>
						</dict>
						<key>name</key>
						<string>comment.line.documentation.starlark</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#string-consume-escape</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#code-tag</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>docstring-content</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-escape-sequence</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#discouraged-string-line-continuation</string>
					</dict>
				</array>
			</dict>
			<key>docstring-statement</key>
			<dict>
				<key>begin</key>
				<string>^(?=\s*r?('''|"""|'|"))</string>
				<key>end</key>
				<string>(?&lt;='''|"""|'|")</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#docstring</string>
					</dict>
				</array>
			</dict>
			<key>expression</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression-base</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#member-access</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#variable</string>
					</dict>
				</array>
			</dict>
			<key>expression-base</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#line-comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#illegal-operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#dictionary-literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#subscript-expression</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#list-literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#parenthesized-expression</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-function</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#constant-identifier</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#type-identifier</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#illegal-name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#line-continuation</string>
					</dict>
				</array>
			</dict>
			<key>function-arguments</key>
			<dict>
				<key>begin</key>
				<string>(?:(\()(?:\s*(\*\*|\*))?)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.arguments.begin.starlark</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.unpacking.arguments.starlark</string>
					</dict>
				</dict>
				<key>contentName</key>
				<string>meta.function-call.arguments.starlark</string>
				<key>end</key>
				<string>(?=\))(?!\)\s*\()</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.arguments.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.unpacking.arguments.starlark</string>
							</dict>
						</dict>
						<key>match</key>
						<string>(?:(,)(?:\s*(\*\*|\*))?)</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#illegal-name</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>meta.parameter.keyword.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.assignment.starlark</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\s*(=)(?!=)</string>
					</dict>
					<dict>
						<key>match</key>
						<string>=(?!=)</string>
						<key>name</key>
						<string>keyword.operator.assignment.starlark</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.arguments.end.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.arguments.begin.starlark</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\s*(\))\s*(\()</string>
					</dict>
				</array>
			</dict>
			<key>function-call</key>
			<dict>
				<key>begin</key>
				<string>\b(?=([[:alpha:]_]\w*)\s*(\())</string>
				<key>end</key>
				<string>(\))</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.arguments.end.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.function-call.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#function-call-name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#function-arguments</string>
					</dict>
				</array>
			</dict>
			<key>function-call-name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#type-identifier</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-function</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
						<key>name</key>
						<string>entity.name.function.starlark</string>
					</dict>
				</array>
			</dict>
			<key>function-definition</key>
			<dict>
				<key>begin</key>
				<string>\s*\b(def)\s+(?=[[:alpha:]_][[:word:]]*\s*\()</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.function.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(:|(?=[#'"\n]))</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.function.begin.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.function.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#function-definition-name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#function-definition-parameters</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#line-continuation</string>
					</dict>
				</array>
			</dict>
			<key>function-definition-name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#builtin-constant</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#illegal-name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-function</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
						<key>name</key>
						<string>entity.name.function.starlark</string>
					</dict>
				</array>
			</dict>
			<key>function-definition-parameter-default-value</key>
			<dict>
				<key>begin</key>
				<string>(=)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(,)|(?=\))</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.separator.parameters.starlark</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>function-definition-parameters</key>
			<dict>
				<key>begin</key>
				<string>(\()</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.parameters.begin.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(\))</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.parameters.end.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.function.parameters.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(\*\*|\*)</string>
						<key>name</key>
						<string>keyword.operator.unpacking.parameter.starlark</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#illegal-name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-constant</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.parameters.starlark</string>
							</dict>
						</dict>
						<key>match</key>
						<string>([[:alpha:]_]\w*)\s*(?:(,)|(?=[)#\n=]))</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#line-comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#function-definition-parameter-default-value</string>
					</dict>
				</array>
			</dict>
			<key>illegal-name</key>
			<dict>
				<key>match</key>
				<string>\b(and|as|assert|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|load|nonlocal|not|or|pass|raise|return|try|while|with|yield)\b</string>
				<key>name</key>
				<string>keyword.control.flow.starlark</string>
			</dict>
			<key>illegal-operator</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>&amp;&amp;|\|\||--|\+\+</string>
						<key>name</key>
						<string>invalid.illegal.operator.starlark</string>
					</dict>
					<dict>
						<key>match</key>
						<string>[?$]</string>
						<key>name</key>
						<string>invalid.illegal.operator.starlark</string>
					</dict>
					<dict>
						<key>match</key>
						<string>!\b</string>
						<key>name</key>
						<string>invalid.illegal.operator.starlark</string>
					</dict>
				</array>
			</dict>
			<key>line-comment</key>
			<dict>
				<key>begin</key>
				<string>(\#)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>($)</string>
				<key>name</key>
				<string>comment.line.number-sign.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#code-tag</string>
					</dict>
				</array>
			</dict>
			<key>line-continuation</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>invalid.deprecated.continuation.line.starlark</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>invalid.illegal.line.continuation.starlark</string>
							</dict>
						</dict>
						<key>match</key>
						<string>(\\)\s*(\S.*$\n?)</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>(\\)\s*$\n?</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>invalid.deprecated.continuation.line.starlark</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(?=^\s*$)|(?!(\s*[rR]?('''|"""|'|"))|(\G$))</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#string</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>list-literal</key>
			<dict>
				<key>begin</key>
				<string>\[</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.list.begin.starlark</string>
					</dict>
				</dict>
				<key>comment</key>
				<string>This also currently covers comprehensions.</string>
				<key>end</key>
				<string>\]</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.list.end.starlark</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>literal</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(True|False|None)\b</string>
						<key>name</key>
						<string>constant.language.starlark</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#number</string>
					</dict>
				</array>
			</dict>
			<key>member-access</key>
			<dict>
				<key>begin</key>
				<string>(\.)\s*(?!\.)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.accessor.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?# Stop when we read non-whitespace followed by non-word; i.e. when finished reading an identifier or function call)(?&lt;=\S)(?=\W)|(?# Stop when seeing the start of something that's not a word; e.g., a non-identifier)(^|(?&lt;=\s))(?=[^\\\w\s])|$</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#member-access-base</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#member-access-property</string>
					</dict>
				</array>
			</dict>
			<key>member-access-base</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#illegal-name</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-constant</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#constant-identifier</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#type-identifier</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#line-continuation</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#subscript-expression</string>
					</dict>
				</array>
			</dict>
			<key>member-access-property</key>
			<dict>
				<key>match</key>
				<string>\b([[:alpha:]_]\w*)\b</string>
				<key>name</key>
				<string>variable.other.property.starlark</string>
			</dict>
			<key>number</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#number-decimal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#number-hexadecimal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#number-octal</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b[0-9]+\w+</string>
						<key>name</key>
						<string>invalid.illegal.name.starlark</string>
					</dict>
				</array>
			</dict>
			<key>number-decimal</key>
			<dict>
				<key>match</key>
				<string>(?&lt;![\w\.])(?:[1-9][0-9]*|0+)\b</string>
				<key>name</key>
				<string>constant.numeric.decimal.starlark</string>
			</dict>
			<key>number-hexadecimal</key>
			<dict>
				<key>match</key>
				<string>(?&lt;![\w\.])0[xX][0-9a-fA-F]+\b</string>
				<key>name</key>
				<string>constant.numeric.hex.starlark</string>
			</dict>
			<key>number-octal</key>
			<dict>
				<key>match</key>
				<string>(?&lt;![\w\.])0[oO][0-7]+\b</string>
				<key>name</key>
				<string>constant.numeric.octal.starlark</string>
			</dict>
			<key>operator</key>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.logical.starlark</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.control.flow.starlark</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.arithmetic.starlark</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.comparison.starlark</string>
					</dict>
				</dict>
				<key>match</key>
				<string>\b(?&lt;!\.)(?:(and|or|not|in)(?# 1)|(for|if|else)(?# 2))(?!\s*:)\b|(\*|\+|-|%|//|/)(?# 3)|(!=|==|&gt;=|&lt;=|&lt;|&gt;)(?# 4)</string>
			</dict>
			<key>parenthesized-expression</key>
			<dict>
				<key>begin</key>
				<string>\(</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.parenthesis.begin.starlark</string>
					</dict>
				</dict>
				<key>comment</key>
				<string>This covers tuples and parenthesized expressions.</string>
				<key>end</key>
				<string>\)</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.parenthesis.end.starlark</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>statement</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#function-definition</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#statement-keyword</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#assignment-operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#docstring-statement</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#discouraged-semicolon</string>
					</dict>
				</array>
			</dict>
			<key>statement-keyword</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(\s*def)\b</string>
						<key>name</key>
						<string>storage.type.function.starlark</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b(?&lt;!\.)(break|continue|elif|else|for|if|pass|return)\b</string>
						<key>name</key>
						<string>keyword.control.flow.starlark</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b(?&lt;!\.)(as|assert|class|del|except|finally|from|global|import|is|lambda|nonlocal|raise|try|while|with|yield)\b</string>
						<key>name</key>
						<string>invalid.illegal.keyword.starlark</string>
					</dict>
				</array>
			</dict>
			<key>string</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-raw-quoted-multi-line</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-raw-quoted-single-line</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-quoted-multi-line</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-quoted-single-line</string>
					</dict>
				</array>
			</dict>
			<key>string-consume-escape</key>
			<dict>
				<key>match</key>
				<string>\\['"\n\\]</string>
			</dict>
			<key>string-content</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-escape-sequence</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-illegal-escape-sequence</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#discouraged-string-line-continuation</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-format-placeholder-percent</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-format-placeholder-braces</string>
					</dict>
				</array>
			</dict>
			<key>string-escape-sequence</key>
			<dict>
				<key>match</key>
				<string>\\[\\"'nrt]</string>
				<key>name</key>
				<string>constant.character.escape.starlark</string>
			</dict>
			<key>string-format-placeholder-braces</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\{(?:[0-9]+|[[:alpha:]_][[:alnum:]_]*)?\}</string>
						<key>name</key>
						<string>constant.character.format.placeholder.other.starlark</string>
					</dict>
				</array>
			</dict>
			<key>string-format-placeholder-percent</key>
			<dict>
				<key>match</key>
				<string>%[drs%]</string>
				<key>name</key>
				<string>constant.character.format.placeholder.other.starlark</string>
			</dict>
			<key>string-illegal-escape-sequence</key>
			<dict>
				<key>match</key>
				<string>\\[^\\"'nrt]</string>
				<key>name</key>
				<string>invalid.illegal.character.escape.starlark</string>
			</dict>
			<key>string-quoted-multi-line</key>
			<dict>
				<key>begin</key>
				<string>('''|""")</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(\1)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.multi.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-content</string>
					</dict>
				</array>
			</dict>
			<key>string-quoted-single-line</key>
			<dict>
				<key>begin</key>
				<string>(['"])</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(\1)|((?&lt;!\\)\n)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.starlark</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>invalid.illegal.newline.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.single.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-content</string>
					</dict>
				</array>
			</dict>
			<key>string-raw-content</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-consume-escape</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-format-placeholder-percent</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string-format-placeholder-braces</string>
					</dict>
				</array>
			</dict>
			<key>string-raw-quoted-multi-line</key>
			<dict>
				<key>begin</key>
				<string>\b(r)('''|""")</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.string.starlark</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(\2)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.raw.multi.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-raw-content</string>
					</dict>
				</array>
			</dict>
			<key>string-raw-quoted-single-line</key>
			<dict>
				<key>begin</key>
				<string>\b(r)(['"])</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.string.starlark</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.starlark</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(\2)|((?&lt;!\\)\n)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.starlark</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>invalid.illegal.newline.starlark</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.raw.single.starlark</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string-raw-content</string>
					</dict>
				</array>
			</dict>
			<key>subscript-expression</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>\b(?=[[:alpha:]_]\w*\s*\[)</string>
						<key>end</key>
						<string>(\])</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.arguments.end.starlark</string>
							</dict>
						</dict>
						<key>name</key>
						<string>meta.item-access.starlark</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#subscript-receiver</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#subscript-index</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#expression</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>subscript-index</key>
			<dict>
				<key>begin</key>
				<string>(\[)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.arguments.begin.starlark</string>
					</dict>
				</dict>
				<key>contentName</key>
				<string>meta.item-access.arguments.starlark</string>
				<key>end</key>
				<string>(?=\])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>subscript-receiver</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#builtin-function</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#constant-identifier</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
						<key>name</key>
						<string>variable.other.starlark</string>
					</dict>
				</array>
			</dict>
			<key>type-identifier</key>
			<dict>
				<key>match</key>
				<string>\b_*[[:upper:]][[:alpha:]\d]*(_\w*)?\b</string>
				<key>name</key>
				<string>entity.name.type.starlark</string>
			</dict>
			<key>variable</key>
			<dict>
				<key>match</key>
				<string>\b([[:alpha:]_]\w*)\b</string>
				<key>name</key>
				<string>variable.other.starlark</string>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>tiltfile.tmLanguage</string>
		<key>uuid</key>
		<string>36137B9B-FDEA-47F9-ADBA-DEF914A318B1</string>
	</dict>
</plist>
